language: go

before_install:
        - echo -e "Starting"
        - echo sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
        - echo wget http://ftp.ps.pl/pub/apache/thrift/0.10.0/thrift-0.10.0.tar.gz
        - echo ls
        - echo tar xfz thrift-0.10.0.tar.gz
        - echo cd thrift-0.10.0 && echo ./configure && echo sudo make install
        - uname -a
        - cat /etc/*eleas*
        - false

script: ./build-rpc-agent.sh --thrift-exec $PWD/thrift --erase-on-steps

