language: go

before_install:
        - echo -e "Starting"
        - sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
        - wget http://www.apache.org/dyn/closer.cgi?path=/thrift/0.10.0/thrift-0.10.0.tar.gz
        - tar xfz thrift-0.10.0.tar.gz
        - cd thrift-0.10.0 && ./configure && sudo make install

script: ./build-rpc-agent.sh --thrift-exec $PWD/thrift --erase-on-steps

